### ISSUE TITLE
Sub-sketch Points Do Not Match

### ISSUE THREAD

**Issue by DaAwesomeP** [abey79/vsketch#158]
Hello,

I am having an issue with sub-sketches and points. Here is an example:
```python3
sub_sketch = vsketch.Vsketch()
sub_sketch.point(0, 0)
vsk.sketch(sub_sketch)
vsk.point(0,0)
```
This produces:
![image](https://user-images.githubusercontent.com/4472083/134821138-bf772fbb-7299-45b9-ba84-a0f13dc548ac.png)
The outer circle is the subsketch point. The inner point is what was expected.

I tried playing with the `penWidth` option in and out of the subsketch to no avail.

**Comment by abey79** [comment]
I can indeed reproduce the bug, thanks for pointing out. This is due to how scaling in the base sketch and sub-sketch interact and I don't have a clear path to fixing this. Fundamentally, I think the sub-sketch idea is flawed and will be super-seeded by the upcoming "shape" feature (#124).

For this particular case, here is a possible work-around (although it does restrict some of the theoretical possibilities of sub-sketches:

```python
    def draw(self, vsk: vsketch.Vsketch) -> None:
        vsk.size("a4", landscape=False)
        vsk.scale("cm")

        sub_sketch = vsketch.Vsketch()
        sub_sketch.scale("cm")
        sub_sketch.rect(-0.5, -0.5, 1, 1)
        sub_sketch.point(0, 0)
        with vsk.resetMatrix():
            vsk.sketch(sub_sketch)
        vsk.point(5, 5)
        vsk.rect(4.5, 4.5, 1, 1)
```

Note the explicit setting of the scale in the sub-sketch (identical to the base sketch's), and the use of `vsk.resetMatrix()`.

**Comment by DaAwesomeP** [comment]
I see, yes this is not ideal. Specifically that you then cannot use `pushMatrix()` and `popMatrix()`. I am trying to place a reusable sequence several places in the drawing. This sequence involves using vpype to crop it to a square, so I have to use sub sketches (unless there is another way). I can build the translate into the function, that is just more tedious than using push and pop.

**Comment by abey79** [comment]
I'm not entirely sure I understand your use-case, but *if* the sub-sketch is to be used at the same scale everywhere, just at various location, then there is a chance you could use `pushMatrix()` & friends "inside" the `resetMatrix()`:

```python
def draw(self, vsk: vsketch.Vsketch) -> None:
    vsk.size("a4", landscape=False)
    vsk.scale("cm")

    sub_sketch = vsketch.Vsketch()
    sub_sketch.scale("cm")
    # build subsketch

    with vsk.resetMatrix():
        for i in range(...):
            for j in range(...):
                with vsk.pushMatrix():
                    vsk.translate(i * ..., j * ...)
                    vsk.sketch(sub_sketch)
```

Because of the `resetMatrix()`, the translate call would need pixels as opposed to centimetre (in the example above) which, clearly, is not ideal.

Again, this is far from ideal. If you feel adventurous, take a look at the `feature-shape` branch (#124). It should cover your use-case better and should be mature enough to experiment -- I just haven't had the time yet to polish and merge it.
